{"timestamp": "2025-05-15T23:48:40.711500", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: 'coroutine' object is not iterable"}
{"timestamp": "2025-05-15T23:48:40.712290", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "TypeError", "message": "'coroutine' object is not iterable", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 217, in process_videos\n    for query in search_queries:\nTypeError: 'coroutine' object is not iterable"}}
{"timestamp": "2025-05-15T23:56:21.849916", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: Falha ao cortar os v\u00eddeos"}
{"timestamp": "2025-05-15T23:56:21.850250", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "Exception", "message": "Falha ao cortar os v\u00eddeos", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 261, in process_videos\n    raise Exception(\"Falha ao cortar os v\u00eddeos\")\nException: Falha ao cortar os v\u00eddeos"}}
{"timestamp": "2025-05-16T14:02:00.416478", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: Falha ao concatenar v\u00eddeos"}
{"timestamp": "2025-05-16T14:02:00.417263", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "Exception", "message": "Falha ao concatenar v\u00eddeos", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 310, in process_videos\n    raise Exception(\"Falha ao concatenar v\u00eddeos\")\nException: Falha ao concatenar v\u00eddeos"}}
{"timestamp": "2025-05-16T14:12:18.129304", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: Falha ao concatenar v\u00eddeos"}
{"timestamp": "2025-05-16T14:12:18.130030", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "Exception", "message": "Falha ao concatenar v\u00eddeos", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 310, in process_videos\n    raise Exception(\"Falha ao concatenar v\u00eddeos\")\nException: Falha ao concatenar v\u00eddeos"}}
{"timestamp": "2025-05-16T14:35:26.418557", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: Falha ao concatenar v\u00eddeos"}
{"timestamp": "2025-05-16T14:35:26.418910", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "Exception", "message": "Falha ao concatenar v\u00eddeos", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 310, in process_videos\n    raise Exception(\"Falha ao concatenar v\u00eddeos\")\nException: Falha ao concatenar v\u00eddeos"}}
{"timestamp": "2025-05-16T14:43:05.299984", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: 'coroutine' object has no attribute 'strip'"}
{"timestamp": "2025-05-16T14:43:05.300328", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "AttributeError", "message": "'coroutine' object has no attribute 'strip'", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 345, in process_videos\n    texto_narrativo = response.strip()\nAttributeError: 'coroutine' object has no attribute 'strip'"}}
{"timestamp": "2025-05-16T14:48:24.364380", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: name 'get_target_resolution' is not defined"}
{"timestamp": "2025-05-16T14:48:24.364743", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "NameError", "message": "name 'get_target_resolution' is not defined", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 185, in process_videos\n    target_resolution = get_target_resolution(format_type)\nNameError: name 'get_target_resolution' is not defined"}}
{"timestamp": "2025-05-16T15:01:53.115349", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: object list can't be used in 'await' expression"}
{"timestamp": "2025-05-16T15:01:53.115811", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "TypeError", "message": "object list can't be used in 'await' expression", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 189, in process_videos\n    search_queries = await generate_search_queries(custom_prompt, num_scenes)\nTypeError: object list can't be used in 'await' expression"}}
{"timestamp": "2025-05-16T15:03:05.492390", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: download_video() missing 1 required positional argument: 'downloaded_ids'"}
{"timestamp": "2025-05-16T15:03:05.492694", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "TypeError", "message": "download_video() missing 1 required positional argument: 'downloaded_ids'", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 197, in process_videos\n    video_path = await download_video(query, site)\nTypeError: download_video() missing 1 required positional argument: 'downloaded_ids'"}}
{"timestamp": "2025-05-16T15:04:44.149019", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: object str can't be used in 'await' expression"}
{"timestamp": "2025-05-16T15:04:44.149261", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "TypeError", "message": "object str can't be used in 'await' expression", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 198, in process_videos\n    video_path = await download_video(query, format_type, downloaded_ids, max_attempts=3, site=site)\nTypeError: object str can't be used in 'await' expression"}}
{"timestamp": "2025-05-16T16:10:08.630249", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: object str can't be used in 'await' expression"}
{"timestamp": "2025-05-16T16:10:08.630988", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "TypeError", "message": "object str can't be used in 'await' expression", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 268, in process_videos\n    texto_narrativo = await response\nTypeError: object str can't be used in 'await' expression"}}
{"timestamp": "2025-05-16T17:04:18.208137", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: [Errno 2] No such file or directory: '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/final_video.mp4' -> '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/video_1747415058.mp4'"}
{"timestamp": "2025-05-16T17:04:18.208535", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "FileNotFoundError", "message": "[Errno 2] No such file or directory: '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/final_video.mp4' -> '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/video_1747415058.mp4'", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 294, in process_videos\n    os.rename(final_video, final_video_path)\nFileNotFoundError: [Errno 2] No such file or directory: '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/final_video.mp4' -> '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/video_1747415058.mp4'"}}
{"timestamp": "2025-05-16T17:25:42.870876", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: [Errno 2] No such file or directory: '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/final_video.mp4' -> '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/video_1747416342.mp4'"}
{"timestamp": "2025-05-16T17:25:42.871301", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "FileNotFoundError", "message": "[Errno 2] No such file or directory: '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/final_video.mp4' -> '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/video_1747416342.mp4'", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 294, in process_videos\n    os.rename(final_video, final_video_path)\nFileNotFoundError: [Errno 2] No such file or directory: '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/final_video.mp4' -> '/home/rafael/Desktop/projetos/yduqs_back/app/arquivosTemporarios/video_1747416342.mp4'"}}
{"timestamp": "2025-05-16T17:40:11.750851", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Erro no processamento: download_video() missing 1 required positional argument: 'downloaded_ids'"}
{"timestamp": "2025-05-16T17:40:11.751310", "level": "ERROR", "logger": "app.videoPexel.video_processing", "message": "Detalhes do erro:", "exception": {"type": "TypeError", "message": "download_video() missing 1 required positional argument: 'downloaded_ids'", "traceback": "Traceback (most recent call last):\n  File \"/home/rafael/Desktop/projetos/yduqs_back/app/videoPexel/video_processing.py\", line 208, in process_videos\n    video_path = await download_video(query, site)\nTypeError: download_video() missing 1 required positional argument: 'downloaded_ids'"}}
